const images = [
  { src: './photos/photo01.jpg', label: 'Sample image 1' },
  { src: './photos/photo02.jpg', label: 'Sample image 2' },
  { src: './photos/photo03.jpg', label: 'Sample image 3' },
  { src: './photos/photo04.jpg', label: 'Sample image 4' },
  { src: './photos/photo05.jpg', label: 'Sample image 5' },
  { src: './photos/photo06.jpg', label: 'Sample image 6' },
  { src: './photos/photo07.jpg', label: 'Sample image 7' },
  { src: './photos/photo08.jpg', label: 'Sample image 8' },
  { src: './photos/photo09.jpg', label: 'Sample image 9' },
  { src: './photos/photo10.jpg', label: 'Sample image 10' },
  { src: './photos/photo11.jpg', label: 'Sample image 11' },
  { src: './photos/photo12.jpg', label: 'Sample image 12' },
  { src: './photos/photo13.jpg', label: 'Sample image 13' },
  { src: './photos/photo14.jpg', label: 'Sample image 14' },
  { src: './photos/photo15.jpg', label: 'Sample image 15' },
  { src: './photos/photo16.jpg', label: 'Sample image 16' },
  { src: './photos/photo17.jpg', label: 'Sample image 17' },
  { src: './photos/photo18.jpg', label: 'Sample image 18' },
  { src: './photos/photo19.jpg', label: 'Sample image 19' },
  { src: './photos/photo20.jpg', label: 'Sample image 20' },
  { src: './photos/photo21.jpg', label: 'Sample image 21' },
  { src: './photos/photo22.jpg', label: 'Sample image 22' },
];

export default images;
